import type {
  HeroDocument,
  BentoCardDocument,
  ProjectDocument,
  TestimonialDocument,
  ClientDocument,
  ExperienceDocument,
  PhaseDocument,
  NavigationDocument,
  CtaDocument,
  FooterDocument,
  SocialLinkDocument,
  SeoDocument,
  PublicPortfolioProjection,
} from "@/types/portfolio";

export const SEED_HERO: HeroDocument = {
  id: "hero_main",
  eyebrow: "Dynamic Web Magic with Next.js",
  headingWords: "Transforming Concepts into Seamless User Experiences",
  description: "Hi! I'm Gaurav, a Next.js Developer based in India.",
  ctaTitle: "Show my work",
  ctaLink: "#projects",
  scrollText: "Scroll Down",
  isPublished: true,
  updatedAt: new Date().toISOString(),
  version: 1,
};

export const SEED_CARDS: BentoCardDocument[] = [
  {
    id: "card_01",
    slotIndex: 1,
    cardType: "collaboration",
    gridSpanVariant: "span_wide",
    visualLayout: "image_bottom",
    title: "I prioritize client collaboration, fostering open communication",
    description: "",
    img: "/b1.svg",
    spareImg: "",
    isPublished: true,
    updatedAt: new Date().toISOString(),
    version: 1,
  },
  {
    id: "card_02",
    slotIndex: 2,
    cardType: "globe_timezone",
    gridSpanVariant: "span_default",
    visualLayout: "globe_canvas",
    title: "I'm very flexible with time zone communications",
    description: "",
    img: "",
    spareImg: "",
    isPublished: true,
    updatedAt: new Date().toISOString(),
    version: 1,
  },
  {
    id: "card_03",
    slotIndex: 3,
    cardType: "tech_stack",
    gridSpanVariant: "span_default",
    visualLayout: "tech_pills",
    title: "My tech stack",
    description: "I constantly try to improve",
    techStackLeft: ["React.js", "Next.js", "TypeScript"],
    techStackRight: ["TailwindCSS", "Node.js", "Firebase"],
    isPublished: true,
    updatedAt: new Date().toISOString(),
    version: 1,
  },
  {
    id: "card_04",
    slotIndex: 4,
    cardType: "passion",
    gridSpanVariant: "span_default",
    visualLayout: "image_bottom",
    title: "Tech enthusiast with a passion for development.",
    description: "",
    img: "/b4.svg",
    spareImg: "/grid.svg",
    isPublished: true,
    updatedAt: new Date().toISOString(),
    version: 1,
  },
  {
    id: "card_05",
    slotIndex: 5,
    cardType: "current_project",
    gridSpanVariant: "span_wide",
    visualLayout: "image_right",
    title: "Currently building a JS Animation library",
    description: "The Inside Scoop",
    img: "/b5.svg",
    spareImg: "/grid.svg",
    isPublished: true,
    updatedAt: new Date().toISOString(),
    version: 1,
  },
  {
    id: "card_06",
    slotIndex: 6,
    cardType: "contact_cta",
    gridSpanVariant: "span_default",
    visualLayout: "centered_text",
    title: "Do you want to start a project together?",
    description: "",
    ctaEmail: "hello@gauravpatil.online",
    isPublished: true,
    updatedAt: new Date().toISOString(),
    version: 1,
  },
];

export const SEED_PROJECTS: ProjectDocument[] = [
  {
    id: "proj_01",
    order: 1,
    title: "3D Solar System Planets to Explore",
    description: "Explore the wonders of our solar system with this captivating 3D simulation of the planets using Three.js.",
    coverImageStoragePath: "/p1.svg",
    coverImage: "/p1.svg",
    iconLists: ["/re.svg", "/tail.svg", "/ts.svg", "/three.svg", "/fm.svg"],
    liveUrl: "https://github.com/AspiringWebGaurav",
    githubUrl: "https://github.com/AspiringWebGaurav",
    isFeatured: true,
    isPublished: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: 1,
  },
  {
    id: "proj_02",
    order: 2,
    title: "Yoom - Video Conferencing App",
    description: "Simplify your video conferencing experience with Yoom. Seamlessly connect with colleagues and friends.",
    coverImageStoragePath: "/p2.svg",
    coverImage: "/p2.svg",
    iconLists: ["/next.svg", "/tail.svg", "/ts.svg", "/stream.svg", "/c.svg"],
    liveUrl: "https://github.com/AspiringWebGaurav",
    githubUrl: "https://github.com/AspiringWebGaurav",
    isFeatured: true,
    isPublished: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: 1,
  },
  {
    id: "proj_03",
    order: 3,
    title: "AI Image SaaS - Canva Application",
    description: "A REAL Software-as-a-Service app with AI features and a payments and credits system using the latest tech stack.",
    coverImageStoragePath: "/p3.svg",
    coverImage: "/p3.svg",
    iconLists: ["/re.svg", "/tail.svg", "/ts.svg", "/three.svg", "/c.svg"],
    liveUrl: "https://github.com/AspiringWebGaurav",
    githubUrl: "https://github.com/AspiringWebGaurav",
    isFeatured: true,
    isPublished: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: 1,
  },
  {
    id: "proj_04",
    order: 4,
    title: "Animated Apple iPhone 3D Website",
    description: "Recreated the Apple iPhone 15 Pro website, combining GSAP animations and Three.js 3D effects..",
    coverImageStoragePath: "/p4.svg",
    coverImage: "/p4.svg",
    iconLists: ["/next.svg", "/tail.svg", "/ts.svg", "/three.svg", "/gsap.svg"],
    liveUrl: "https://github.com/AspiringWebGaurav",
    githubUrl: "https://github.com/AspiringWebGaurav",
    isFeatured: true,
    isPublished: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: 1,
  },
];

export const SEED_TESTIMONIALS: TestimonialDocument[] = [
  {
    id: "test_01",
    order: 1,
    quote: "Collaborating with Gaurav was an absolute pleasure. His professionalism, promptness, and dedication to delivering exceptional results were evident throughout our project. Gaurav's enthusiasm for every facet of development truly stands out. If you're seeking to elevate your website and elevate your brand, Gaurav is the ideal partner.",
    name: "Michael Johnson",
    role: "Director of AlphaStream Technologies",
    company: "AlphaStream",
    avatarStoragePath: "/profile.svg",
    avatarUrl: "/profile.svg",
    isPublished: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: 1,
  },
  {
    id: "test_02",
    order: 2,
    quote: "Collaborating with Gaurav was an absolute pleasure. His professionalism, promptness, and dedication to delivering exceptional results were evident throughout our project. Gaurav's enthusiasm for every facet of development truly stands out. If you're seeking to elevate your website and elevate your brand, Gaurav is the ideal partner.",
    name: "Michael Johnson",
    role: "Director of AlphaStream Technologies",
    company: "AlphaStream",
    avatarStoragePath: "/profile.svg",
    avatarUrl: "/profile.svg",
    isPublished: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: 1,
  },
  {
    id: "test_03",
    order: 3,
    quote: "Collaborating with Gaurav was an absolute pleasure. His professionalism, promptness, and dedication to delivering exceptional results were evident throughout our project. Gaurav's enthusiasm for every facet of development truly stands out. If you're seeking to elevate your website and elevate your brand, Gaurav is the ideal partner.",
    name: "Michael Johnson",
    role: "Director of AlphaStream Technologies",
    company: "AlphaStream",
    avatarStoragePath: "/profile.svg",
    avatarUrl: "/profile.svg",
    isPublished: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: 1,
  },
  {
    id: "test_04",
    order: 4,
    quote: "Collaborating with Gaurav was an absolute pleasure. His professionalism, promptness, and dedication to delivering exceptional results were evident throughout our project. Gaurav's enthusiasm for every facet of development truly stands out. If you're seeking to elevate your website and elevate your brand, Gaurav is the ideal partner.",
    name: "Michael Johnson",
    role: "Director of AlphaStream Technologies",
    company: "AlphaStream",
    avatarStoragePath: "/profile.svg",
    avatarUrl: "/profile.svg",
    isPublished: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: 1,
  },
  {
    id: "test_05",
    order: 5,
    quote: "Collaborating with Gaurav was an absolute pleasure. His professionalism, promptness, and dedication to delivering exceptional results were evident throughout our project. Gaurav's enthusiasm for every facet of development truly stands out. If you're seeking to elevate your website and elevate your brand, Gaurav is the ideal partner.",
    name: "Michael Johnson",
    role: "Director of AlphaStream Technologies",
    company: "AlphaStream",
    avatarStoragePath: "/profile.svg",
    avatarUrl: "/profile.svg",
    isPublished: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: 1,
  },
];

export const SEED_CLIENTS: ClientDocument[] = [
  {
    id: "client_01",
    order: 1,
    name: "cloudinary",
    iconStoragePath: "/cloud.svg",
    iconUrl: "/cloud.svg",
    nameImgStoragePath: "/cloudName.svg",
    nameImgUrl: "/cloudName.svg",
    websiteUrl: "https://cloudinary.com",
    logoWidth: 40,
    isPublished: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: 1,
  },
  {
    id: "client_02",
    order: 2,
    name: "appwrite",
    iconStoragePath: "/app.svg",
    iconUrl: "/app.svg",
    nameImgStoragePath: "/appName.svg",
    nameImgUrl: "/appName.svg",
    websiteUrl: "https://appwrite.io",
    logoWidth: 60,
    isPublished: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: 1,
  },
  {
    id: "client_03",
    order: 3,
    name: "HOSTINGER",
    iconStoragePath: "/host.svg",
    iconUrl: "/host.svg",
    nameImgStoragePath: "/hostName.svg",
    nameImgUrl: "/hostName.svg",
    websiteUrl: "https://hostinger.com",
    logoWidth: 60,
    isPublished: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: 1,
  },
  {
    id: "client_04",
    order: 4,
    name: "stream",
    iconStoragePath: "/s.svg",
    iconUrl: "/s.svg",
    nameImgStoragePath: "/streamName.svg",
    nameImgUrl: "/streamName.svg",
    websiteUrl: "https://getstream.io",
    logoWidth: 50,
    isPublished: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: 1,
  },
  {
    id: "client_05",
    order: 5,
    name: "docker.",
    iconStoragePath: "/dock.svg",
    iconUrl: "/dock.svg",
    nameImgStoragePath: "/dockerName.svg",
    nameImgUrl: "/dockerName.svg",
    websiteUrl: "https://docker.com",
    logoWidth: 50,
    isPublished: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: 1,
  },
];

export const SEED_EXPERIENCE: ExperienceDocument[] = [
  {
    id: "exp_01",
    order: 1,
    title: "Frontend Engineer Intern",
    description: "Assisted in the development of a web-based platform using React.js, enhancing interactivity.",
    company: "Tech Labs",
    period: "2023 - 2024",
    thumbnailStoragePath: "/exp1.svg",
    thumbnailUrl: "/exp1.svg",
    isPublished: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: 1,
  },
  {
    id: "exp_02",
    order: 2,
    title: "Mobile App Dev - JSM Tech",
    description: "Designed and developed mobile app for both iOS & Android platforms using React Native.",
    company: "JSM Tech",
    period: "2024",
    thumbnailStoragePath: "/exp2.svg",
    thumbnailUrl: "/exp2.svg",
    isPublished: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: 1,
  },
  {
    id: "exp_03",
    order: 3,
    title: "Freelance App Dev Project",
    description: "Led the dev of a mobile app for a client, from initial concept to deployment on app stores.",
    company: "Independent",
    period: "2024 - 2025",
    thumbnailStoragePath: "/exp3.svg",
    thumbnailUrl: "/exp3.svg",
    isPublished: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: 1,
  },
  {
    id: "exp_04",
    order: 4,
    title: "Lead Frontend Developer",
    description: "Developed and maintained user-facing features using modern frontend technologies.",
    company: "Dev Studio",
    period: "2025 - Present",
    thumbnailStoragePath: "/exp4.svg",
    thumbnailUrl: "/exp4.svg",
    isPublished: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: 1,
  },
];

export const SEED_PHASES: PhaseDocument[] = [
  {
    id: "phase_01",
    order: 1,
    phaseBadge: "Phase 1",
    title: "Planning & Strategy",
    description: "We'll collaborate to map out your website's goals, target audience, and key functionalities. We'll discuss things like site structure, navigation, and content requirements.",
    themeColor: "emerald",
    animationSpeed: 5.1,
    isPublished: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: 1,
  },
  {
    id: "phase_02",
    order: 2,
    phaseBadge: "Phase 2",
    title: "Development & Progress Update",
    description: "Once we agree on the plan, I cue my lofi playlist and dive into coding. From initial sketches to polished code, I keep you updated every step of the way.",
    themeColor: "pink",
    animationSpeed: 3.0,
    isPublished: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: 1,
  },
  {
    id: "phase_03",
    order: 3,
    phaseBadge: "Phase 3",
    title: "Development & Launch",
    description: "This is where the magic happens! Based on the approved design, I'll build your website from the ground up, ensuring everything is responsive, performant, and accessible.",
    themeColor: "sky",
    animationSpeed: 3.0,
    isPublished: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: 1,
  },
];

export const SEED_NAVIGATION: NavigationDocument = {
  id: "nav_main",
  items: [
    { id: "nav_about", name: "About", link: "#about", order: 1, isVisible: true },
    { id: "nav_projects", name: "Projects", link: "#projects", order: 2, isVisible: true },
    { id: "nav_testimonials", name: "Testimonials", link: "#testimonials", order: 3, isVisible: true },
    { id: "nav_contact", name: "Contact", link: "#contact", order: 4, isVisible: true },
  ],
  updatedAt: new Date().toISOString(),
  version: 1,
};

export const SEED_CTA: CtaDocument = {
  id: "cta_main",
  headingPrefix: "Ready to take ",
  headingHighlight: "your",
  headingSuffix: " digital presence to the next level?",
  description: "Reach out to me today and let's discuss how I can help you achieve your goals.",
  buttonText: "Let's get in touch",
  isEnabled: true,
  updatedAt: new Date().toISOString(),
  version: 1,
};

export const SEED_FOOTER: FooterDocument = {
  id: "footer_main",
  copyrightName: "Gaurav",
  termsUrl: "/terms",
  privacyUrl: "/privacy",
  updatedAt: new Date().toISOString(),
  version: 1,
};

export const SEED_SOCIAL_LINKS: SocialLinkDocument[] = [
  {
    id: "soc_01",
    order: 1,
    platform: "GitHub",
    url: "https://github.com/AspiringWebGaurav",
    iconType: "preset",
    presetName: "github",
    isPublished: true,
    updatedAt: new Date().toISOString(),
    version: 1,
  },
  {
    id: "soc_02",
    order: 2,
    platform: "Twitter",
    url: "https://twitter.com",
    iconType: "preset",
    presetName: "twitter",
    isPublished: true,
    updatedAt: new Date().toISOString(),
    version: 1,
  },
  {
    id: "soc_03",
    order: 3,
    platform: "LinkedIn",
    url: "https://linkedin.com",
    iconType: "preset",
    presetName: "linkedin",
    isPublished: true,
    updatedAt: new Date().toISOString(),
    version: 1,
  },
];

export const SEED_SEO: SeoDocument = {
  id: "seo_main",
  title: "Gaurav's Portfolio",
  description: "Modern, Slick and Minimalist Developer Portfolio",
  canonicalUrl: "https://gauravpatil.online",
  ogImageStoragePath: "",
  ogImageUrl: "",
  keywords: ["Developer", "Portfolio", "Frontend", "Next.js", "React", "TypeScript"],
  author: "Gaurav Patil",
  twitterHandle: "@gauravpatil",
  updatedAt: new Date().toISOString(),
  version: 1,
};

export const SEED_PORTFOLIO_PROJECTION: PublicPortfolioProjection = {
  navigation: SEED_NAVIGATION.items,
  hero: SEED_HERO,
  cards: SEED_CARDS,
  projects: SEED_PROJECTS,
  testimonials: SEED_TESTIMONIALS,
  clients: SEED_CLIENTS,
  experience: SEED_EXPERIENCE,
  phases: SEED_PHASES,
  cta: SEED_CTA,
  footer: SEED_FOOTER,
  socialLinks: SEED_SOCIAL_LINKS,
  seo: SEED_SEO,
};
